'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

type Lang = 'en' | 'ar';
interface LangContextType {
  lang: Lang;
  toggleLang: () => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<string, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    clients: 'Clients',
    projects: 'Projects',
    tasks: 'Tasks',
    assets: 'Assets',
    docs: 'Docs',
    reports: 'Reports',
    team: 'Team',
    settings: 'Settings',
    notifications: 'Notifications',
    security: 'Security',
    logout: 'Log out',
    search: 'Search...',
    welcomeBack: 'Welcome back',
    totalClients: 'Total Clients',
    activeTasks: 'Active Tasks',
    overdueTasks: 'Overdue Tasks',
    recentActivity: 'Recent Activity',
    newClient: 'Add Client',
    companyName: 'Company Name',
    email: 'Email',
    phone: 'Phone',
    website: 'Website',
    industry: 'Industry',
    status: 'Status',
    notes: 'Notes',
    cancel: 'Cancel',
    save: 'Save',
    active: 'Active',
    inactive: 'Inactive',
    prospect: 'Prospect',
    overview: 'Overview',
    content: 'Content',
    activity: 'Activity',
    newTask: 'New Task',
    newContent: 'New content',
    title: 'Title',
    description: 'Description',
    priority: 'Priority',
    dueDate: 'Due Date',
    date: 'Date',
    today: 'Today',
    upcoming: 'Upcoming',
    all: 'All',
    clearFilters: 'Clear filters',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    todo: 'To Do',
    inProgress: 'In Progress',
    done: 'Done',
    overdue: 'Overdue',
    uploadFile: 'Upload File',
    noClientsYet: 'No clients yet',
    noClientsDesc: 'Add your first client to get started',
    noTasksYet: 'No tasks yet',
    noTasksDesc: 'Create your first task to get started',
    noAssetsYet: 'No assets yet',
    noAssetsDesc: 'Upload your first file to get started',
    loading: 'Loading...',
    loginTitle: 'Sign in to OPENY OS',
    registerTitle: 'Sign in to your workspace',
    password: 'Password',
    name: 'Full Name',
    signIn: 'Sign In',
    signUp: 'Admin-provisioned access',
    noAccount: 'Need access?',
    hasAccount: 'Already have access?',
    contentDistribution: 'Content Distribution',
    inprogress: 'In Progress',
    assignedTo: 'Assigned To',
    createdBy: 'Created By',
    mentions: 'Mentions',
    tags: 'Tags (comma separated)',
    taskDetails: 'Task Details',
    editTask: 'Edit Task',
    deleteTask: 'Delete Task',
    confirmDeleteTask: 'Are you sure you want to delete this task? This cannot be undone.',
    changeStatus: 'Change Status',
    reassign: 'Reassign',
    filterByClient: 'Filter by Client',
    filterByAssigned: 'Filter by Assigned',
    filterByPriority: 'Filter by Priority',
    allClients: 'All Clients',
    allMembers: 'All Members',
    allPriorities: 'All Priorities',
    noTeamMembers: 'No team members yet',
    noTeamMembersDesc: 'Add team members to assign tasks',
    newMember: 'New Member',
    fullName: 'Full Name',
    role: 'Role',
    activityHistory: 'Activity History',
    taskCreated: 'Task created',
    taskUpdated: 'Task updated',
    taskDeleted: 'Task deleted',
    upcomingDeadline: 'Due soon',
    selectTeamMember: 'Select team member',
    none: 'None',
    unassigned: 'Unassigned',
    deadline: 'Deadline',
    createdOn: 'Created',
    calendar: 'Calendar',
    myTasks: 'My Tasks',
    review: 'In Review',
    delivered: 'Delivered',
    startDate: 'Start Date',
    tasksDueToday: 'Due Today',
    tasksOverdue: 'Overdue',
    tasksInProgress: 'In Progress',
    tasksInReview: 'In Review',
    tasksCompleted: 'Completed',
    kanban: 'Kanban',
    list: 'List',
    tasksDueThisWeek: 'Due This Week',
    searchTasks: 'Search tasks...',
    allTeamMembers: 'All Team Members',
    allTasks: 'All Tasks',
    noTasksInSection: 'No tasks in this section',
    pleaseSelectClient: 'Please select a client',
    pleaseAssignMember: 'Please assign to a team member',
    pleaseSetDueDate: 'Please set a due date',
    noTasksKanban: 'No tasks',
    overdueCount: 'overdue',
    home: 'Home',
    profile: 'Profile',
    open: 'Open',
    quickActions: 'Quick actions',
    quickAdd: 'Quick add',
    openRightPageToAdd: 'Open the right page to add your item — the form will open automatically.',
    openTasks: 'Open Tasks',
    openClients: 'Open Clients',
    openProjects: 'Open Projects',
    openNotes: 'Open Notes',
    openContent: 'Open Content',
    openAssets: 'Open Assets',
    switchToDark: 'Switch to dark mode',
    switchToLight: 'Switch to light mode',
    newProject: 'New project',
    newNote: 'New note',
    uploadAsset: 'Upload asset',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    clients: 'العملاء',
    projects: 'المشاريع',
    tasks: 'المهام',
    assets: 'الملفات',
    docs: 'المستندات',
    reports: 'التقارير',
    team: 'الفريق',
    settings: 'الإعدادات',
    notifications: 'الإشعارات',
    security: 'الأمان',
    logout: 'تسجيل الخروج',
    search: 'بحث...',
    welcomeBack: 'مرحباً بعودتك',
    totalClients: 'إجمالي العملاء',
    activeTasks: 'المهام النشطة',
    overdueTasks: 'المهام المتأخرة',
    recentActivity: 'النشاط الأخير',
    newClient: 'عميل جديد',
    companyName: 'اسم الشركة',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    website: 'الموقع الإلكتروني',
    industry: 'الصناعة',
    status: 'الحالة',
    notes: 'ملاحظات',
    cancel: 'إلغاء',
    save: 'حفظ',
    active: 'نشط',
    inactive: 'غير نشط',
    prospect: 'محتمل',
    overview: 'نظرة عامة',
    content: 'المحتوى',
    activity: 'النشاط',
    newTask: 'مهمة جديدة',
    newContent: 'محتوى جديد',
    title: 'العنوان',
    description: 'الوصف',
    priority: 'الأولوية',
    dueDate: 'تاريخ الاستحقاق',
    date: 'التاريخ',
    today: 'اليوم',
    upcoming: 'القادمة',
    all: 'الكل',
    clearFilters: 'مسح الفلاتر',
    low: 'منخفضة',
    medium: 'متوسطة',
    high: 'عالية',
    todo: 'للتنفيذ',
    inProgress: 'قيد التنفيذ',
    done: 'مكتمل',
    overdue: 'متأخر',
    uploadFile: 'رفع ملف',
    noClientsYet: 'لا يوجد عملاء بعد',
    noClientsDesc: 'أضف عميلك الأول للبدء',
    noTasksYet: 'لا توجد مهام بعد',
    noTasksDesc: 'أنشئ مهمتك الأولى للبدء',
    noAssetsYet: 'لا توجد ملفات بعد',
    noAssetsDesc: 'ارفع ملفك الأول للبدء',
    loading: 'جار التحميل...',
    loginTitle: 'تسجيل الدخول إلى OPENY OS',
    registerTitle: 'تسجيل الدخول إلى مساحة العمل',
    password: 'كلمة المرور',
    name: 'الاسم الكامل',
    signIn: 'تسجيل الدخول',
    signUp: 'الوصول يتم من قبل مسؤول النظام',
    noAccount: 'تحتاج إلى وصول؟',
    hasAccount: 'لديك وصول بالفعل؟',
    contentDistribution: 'توزيع المحتوى',
    inprogress: 'قيد التنفيذ',
    assignedTo: 'مسند إلى',
    createdBy: 'أنشئ بواسطة',
    mentions: 'الإشارات',
    tags: 'الوسوم (مفصولة بفاصلة)',
    taskDetails: 'تفاصيل المهمة',
    editTask: 'تعديل المهمة',
    deleteTask: 'حذف المهمة',
    confirmDeleteTask: 'هل أنت متأكد من حذف هذه المهمة؟ لا يمكن التراجع عن هذا الإجراء.',
    changeStatus: 'تغيير الحالة',
    reassign: 'إعادة إسناد',
    filterByClient: 'تصفية حسب العميل',
    filterByAssigned: 'تصفية حسب المسند إليه',
    filterByPriority: 'تصفية حسب الأولوية',
    allClients: 'جميع العملاء',
    allMembers: 'جميع الأعضاء',
    allPriorities: 'جميع الأولويات',
    noTeamMembers: 'لا يوجد أعضاء فريق بعد',
    noTeamMembersDesc: 'أضف أعضاء الفريق لإسناد المهام',
    newMember: 'عضو جديد',
    fullName: 'الاسم الكامل',
    role: 'الدور',
    activityHistory: 'سجل النشاط',
    taskCreated: 'تم إنشاء المهمة',
    taskUpdated: 'تم تحديث المهمة',
    taskDeleted: 'تم حذف المهمة',
    upcomingDeadline: 'موعد قريب',
    selectTeamMember: 'اختر عضو الفريق',
    none: 'لا يوجد',
    unassigned: 'غير مسند',
    deadline: 'الموعد النهائي',
    createdOn: 'تاريخ الإنشاء',
    calendar: 'التقويم',
    myTasks: 'مهامي',
    review: 'قيد المراجعة',
    delivered: 'تم التسليم',
    startDate: 'تاريخ البدء',
    tasksDueToday: 'مستحقة اليوم',
    tasksOverdue: 'متأخرة',
    tasksInProgress: 'قيد التنفيذ',
    tasksInReview: 'قيد المراجعة',
    tasksCompleted: 'مكتملة',
    kanban: 'كانبان',
    list: 'قائمة',
    tasksDueThisWeek: 'مستحقة هذا الأسبوع',
    searchTasks: 'بحث في المهام...',
    allTeamMembers: 'جميع أعضاء الفريق',
    allTasks: 'جميع المهام',
    noTasksInSection: 'لا توجد مهام في هذا القسم',
    pleaseSelectClient: 'الرجاء اختيار عميل',
    pleaseAssignMember: 'الرجاء تعيين عضو في الفريق',
    pleaseSetDueDate: 'الرجاء تحديد تاريخ الاستحقاق',
    noTasksKanban: 'لا توجد مهام',
    overdueCount: 'متأخر',
    home: 'الرئيسية',
    profile: 'الملف الشخصي',
    open: 'فتح',
    quickActions: 'إجراءات سريعة',
    quickAdd: 'إضافة سريعة',
    openRightPageToAdd: 'افتح الصفحة المناسبة للإضافة — سيتم فتح النموذج تلقائيًا.',
    openTasks: 'فتح المهام',
    openClients: 'فتح العملاء',
    openProjects: 'فتح المشاريع',
    openNotes: 'فتح الملاحظات',
    openContent: 'فتح المحتوى',
    openAssets: 'فتح الملفات',
    switchToDark: 'التبديل إلى الوضع الداكن',
    switchToLight: 'التبديل إلى الوضع الفاتح',
    newProject: 'مشروع جديد',
    newNote: 'ملاحظة جديدة',
    uploadAsset: 'رفع ملف',
  },
};

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');

  useEffect(() => {
    const saved = localStorage.getItem('lang') as Lang | null;
    if (saved) {
      setLang(saved);
      document.documentElement.setAttribute('lang', saved);
      document.documentElement.setAttribute('dir', saved === 'ar' ? 'rtl' : 'ltr');
    }
  }, []);

  const toggleLang = () => {
    setLang((prev) => {
      const next = prev === 'en' ? 'ar' : 'en';
      localStorage.setItem('lang', next);
      document.documentElement.setAttribute('lang', next);
      document.documentElement.setAttribute('dir', next === 'ar' ? 'rtl' : 'ltr');
      return next;
    });
  };

  const t = (key: string) => translations[lang]?.[key] ?? key;

  return (
    <LangContext.Provider value={{ lang, toggleLang, t, dir: lang === 'ar' ? 'rtl' : 'ltr' }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used inside LangProvider');
  return ctx;
}
